FROM python:3.12.5-slim-bullseye

RUN mkdir /workspace
WORKDIR /workspace
COPY backend/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY backend/src /workspace/src
CMD ["uvicorn", "src.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]