services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    image: frontend_container:dev
    tty: true
    ports:
      - 5173:5173
    environment:
      - VITE_API_URL=http://localhost:8080/api
    volumes:
      - ./frontend:/workspace:cached
      - node_modules:/workspace/node_modules
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
      target: dev
    image: backend_container:dev
    tty: true
    volumes:
      - ./backend/src:/workspace/src
      - ./backend/tests:/workspace/tests
      - ./firebase-adminsdk.json:/workspace/firebase-adminsdk.json
    ports:
      - 8080:8080
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db-container
      - HOST_NAME=db
      - PORT_NUMBER=5432
      - GOOGLE_APPLICATION_CREDENTIALS=/workspace/firebase-adminsdk.json
    depends_on:
      - db
  batch:
    build:
      context: ./batch
      dockerfile: dockerfile
      target: dev
    image: batch_container:dev
    tty: true
    volumes:
      - ./batch/task/app:/app
    ports:
      - 8000:8080
    env_file:
      - batch/env/dev.env
    depends_on:
      - db
  db:
    image: postgres:16.3
    tty: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-container
    ports:
      - 5432:5432
    volumes: # 名前付きボリュームの割り当て定義を追加
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  node_modules:
  db-data:
    driver: local
    # external: true
