services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/dockerfile
    image: frontend_container
    container_name: frontend_container
    tty: true
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/workspace:cached
      - node_modules:/workspace/node_modules
  batch:
    build:
      context: .
      dockerfile: docker/batch/dockerfile
    image: batch_container
    container_name: batch_container
    tty: true
    ports:
      - 8080:8080
    env_file:
      - batch/env/dev.env
    depends_on:
      - db
  db:
    image: postgres:16.3
    container_name: db_container
    tty: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-container
    # volumes:
    #   - ".docker/mysql:/home"
    ports:
      - 5432:5432
    volumes: # 名前付きボリュームの割り当て定義を追加
      - db-data:/var/lib/postgresql/data

volumes:
  node_modules:
  db-data:
    driver: local
    # external: true